Neovici/cosmoz-image-viewer

bower.json, cosmoz-image-viewer.html, cosmoz-image-viewer.js, demo/index.html, photoswipe-boilerplate.html, test/.eslintrc.json, test/basic.html, test/index.html
Fixed:
- detach
- zoom (photoswipe opens)
Enhancement:
-Tapping on the image should display photoswipe rather than on a zoom button?
=> Initial fix

.gitignore, cosmoz-image-viewer.js
See https://github.com/Neovici/cosmoz-image-viewer/issues/9
=> Fixed display of 0 if no images loaded

cosmoz-image-viewer.js
see https://github.com/Neovici/cosmoz-image-viewer/issues/21
=> Changing images list might not change display [issue-21]

.codeclimate.yml, .eslintignore, .gitignore, .travis.yml, analysis.json, cosmoz-image-viewer.js, package.json, test/index.html, wct.conf.json, yarn.lock
fixes https://github.com/Neovici/cosmoz-image-viewer/issues/23
=> Tests code coverage and code climate config v2

cosmoz-image-viewer.js
openFullScreen function fix; it wasn't working on Firefox.
fixes https://github.com/Neovici/cosmoz-image-viewer/issues/26
=> fix imageOverlay

cosmoz-image-viewer.js
Cleanup events and debouncers on detach
=> Cleanup events and debouncers on detach

.eslintrc.json, cosmoz-image-viewer.js, demo/index.html, demo/issue-21.html, test/basic.html, yarn.lock
fixes https://github.com/Neovici/cosmoz-image-viewer/issues/25
code coverage from 35% to
Statements   : 91.96% ( 103/112 )
Branches     : 87.5% ( 42/48 )
Functions    : 96.15% ( 25/26 )
Lines        : 91.89% ( 102/111 )
=> New Tests added

test/basic.html
fix el.viewer undefined.
fixes: https://github.com/Neovici/cosmoz-image-viewer/issues/34
=> fix test - zoomToogle resets zoom: waitForImages

.eslintrc.json, bower.json, cosmoz-image-viewer.html, cosmoz-image-viewer.js
=> Detached window in template tag [issue #32]

cosmoz-image-viewer.html, cosmoz-image-viewer.js
Display image loading error, should be added for attached/docked
mode as well
=> Add basic image load error handling for external window

README.md
This pull request prepares the component for publication on webcomponents.org, following this guide:
https://www.webcomponents.org/publish
Want 2 approves on this.
=> Preparations for Webcomponents.org publication

README.md
This pull request updates the demo section of the read me file. This demo is visible on webcomponents.org.
Please advice if you know better how to do the demo.
Want 2 approves or a merge.
=> Updating demo in read me

.eslintrc.json, bower.json, cosmoz-image-viewer.html, cosmoz-image-viewer.js, test/basic.html, test/detach.html, test/index.html
- Fixes the file downloads in the detached window (downloads now a zip archive)
- Fixes the display of the page number when printing
- Class-based detached window script
=> Download zip & Print fix & Class-based detached window code

.travis.yml, bower.json, cosmoz-image-viewer.html, cosmoz-image-viewer.js, demo/index.html, test/basic.html
Please merge https://github.com/Neovici/img-pan-zoom/pull/1 first.
=> Handle image loading error (in non-detached window)

cosmoz-image-viewer.html
=> host overflow auto

bower.json, cosmoz-image-viewer.html, cosmoz-image-viewer.js, demo/index.html, test/basic.html
I removed the iron-image dependency.
This is a breaking change regarding styling.
(Needs to be tested in FE but cannot access staging atm..)
=> Iron image removal

.codeclimate.yml, .travis.yml, .vscode/settings.json, analysis.json, bower.json, cosmoz-image-viewer-overlay.html, cosmoz-image-viewer.html, cosmoz-image-viewer.js, demo/index.html, index.html, package-lock.json, package.json, polymer.json, test/basic.html, wct.conf.json, yarn.lock
=> Polymer 2.x upgrade

bower.json, cosmoz-image-viewer.html
Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>
=> Re-add iron-image to avoid getting stuck on v1.3.2

cosmoz-image-viewer.js
Component, replacing behaviors with mixins.
Testing, run `yarn install; yarn start`, add `demo/` to the address.
Issue is https://github.com/Neovici/cosmoz-frontend/issues/815.
=> Component, replacing behaviors with mixins

cosmoz-image-viewer.js
Fixes #67 
Might prevent mem leak?
=> Call super.disconnectedCallback();

cosmoz-image-viewer.js, demo/index.html, demo/issue-21.html
https://github.com/Neovici/cosmoz-frontend/issues/1314
=> (patch) modulizer erroneously escaped `attr$=` to `attr\$=`

cosmoz-image-viewer.js
Needed one well placed space for fix.
=> Print icon did not show

cosmoz-image-viewer.html.js
=> (patch) pagination adjustment off center for one page invoices in separate window

cosmoz-image-viewer.js, lib/hooks/use-mouse-pan.js, lib/hooks/use-pan-zoom.js, lib/hooks/use-pan.js, lib/hooks/use-pinch.js, lib/hooks/use-touch-pan.js, lib/reducers/pan-zoom.js, lib/reducers/pinch.js, lib/reducers/touch-pan.js, package-lock.json, test/basic.html, test/detach.html, test/haunted-pan-zoom.html, test/helpers/index.js, test/hooks/use-mouse-pan_test.js, test/hooks/use-pinch_test.js, test/hooks/use-touch-pan_test.js
=> Adjust for new eslint rules (quote-props, cons const)

.github/workflows/workflow.yml, package-lock.json, package.json
Re https://github.com/semantic-release/semantic-release/issues/1194
=> chore: update semantic-release to work with github actions

.github/workflows/workflow.yml, package-lock.json, package.json
This will prevent commits with commit messages that do not adhere to the Conventional Commits spec.
=> chore(dev): enforce conventional commit messages

.vscode/settings.json, lib/haunted-pan-zoom.js, lib/hooks/use-dispatch-event.js, lib/hooks/use-mouse-pan.js, lib/hooks/use-pan-zoom.js, lib/hooks/use-pan.js, lib/hooks/use-pinch.js, lib/hooks/use-public-api.js, lib/hooks/use-resize.js, lib/hooks/use-spring.js, lib/hooks/use-touch-pan.js, lib/reducers/mouse-pan.js, lib/reducers/pan-zoom.js, lib/reducers/pinch.js, lib/reducers/touch-pan.js, lib/utils.js, test/basic.html, test/haunted-pan-zoom.html, test/helpers/index.js, test/hooks/use-mouse-pan_test.js, test/hooks/use-pinch_test.js, test/hooks/use-touch-pan_test.js
Evaluate some style options when it comes to decomposition.
=> chore: linting

lib/pdf.js
Fixes wrong fit function in lib/pdf.js
=> fix: correct pdf fit

lib/pdf.js, package-lock.json, package.json
=> fix: update to jspdf version without file-saver

README.md, web-test-runner.config.mjs
exclude test helpers from coverage
=> chore(test): exclude helpers from coverage

cosmoz-image-viewer.html.js
css intead of old pr: https://github.com/Neovici/cosmoz-image-viewer/pull/155
=> feat(hide buttons): only show on hover

README.md, cosmoz-image-viewer-overlay.js, cosmoz-image-viewer.html.js, cosmoz-image-viewer.js, lib/hooks/use-cosmoz-image-viewer.js, lib/utils.js, package-lock.json, package.json, test/basic.test.js, web-test-runner.config.mjs
BREAKING CHANGE: dropped show-dots and currentImage
=> feat!: replace skeleton-carousel with cosmoz-slider

package-lock.json, package.json
BREAKING CHANGE: cosmoz-utils upgrade.
=> feat(deps): upgrade cosmoz-utils

package-lock.json
jspdf includes dompurify, which had a vulnerability
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1726658957817969
=> fix: upgrade jspdf
